config:
  name: "Updated Test Agent"
  model: "gpt-4o"
  personality: "Helpful test assistant"
  temperature: 0.7
  maxTokens: 1000

capabilities:
  expertise: "testing"
  complexity: "basic"

metadata:
  version: "1.0.0"
  author: "Test Suite"
  description: "Agent for integration testing"
