# N8n Raspberry Pi Docker Compose Setup
# Optimized for ARM64 architecture and 24/7 uptime
version: '3.8'

services:
  # PostgreSQL Database (ARM64 optimized)
  postgres:
    image: postgres:15-alpine
    container_name: n8n_postgres_rpi
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-n8n}
      - POSTGRES_USER=${POSTGRES_USER:-n8n_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-n8n_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - "5432:5432"
    networks:
      - n8n_network
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER:-n8n_user} -d ${POSTGRES_DB:-n8n}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis for Caching (ARM64 optimized)
  redis:
    image: redis:7-alpine
    container_name: n8n_redis_rpi
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - n8n_network
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: redis-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  # N8n Main Application (ARM64 compatible)
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_rpi
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Basic Configuration
      - N8N_HOST=${N8N_HOST:-0.0.0.0}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_LISTEN_ADDRESS=0.0.0.0
      
      # Database Configuration (PostgreSQL)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n_user}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8n_password}
      
      # Redis Configuration
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
      
      # Security & Authentication
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme123}
      - N8N_SECURE_COOKIE=false
      
      # Execution Settings (Optimized for Pi)
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      - EXECUTIONS_DATA_MAX_AGE=168 # Keep executions for 1 week
      - EXECUTIONS_TIMEOUT=300 # 5 minutes timeout for workflows
      - EXECUTIONS_TIMEOUT_MAX=600 # 10 minutes max timeout
      
      # Performance Settings (Pi optimized)
      - N8N_PAYLOAD_DEFAULT_MAX_SIZE=8 # 8MB max payload (reduced for Pi)
      - N8N_METRICS=true
      - NODE_OPTIONS=--max-old-space-size=1024 # Limit Node.js memory to 1GB
      
      # Webhook Settings
      - WEBHOOK_URL=http://${RPI_IP:-localhost}:5678/
      
      # Timezone
      - GENERIC_TIMEZONE=${TIMEZONE:-America/New_York}
      - TZ=${TIMEZONE:-America/New_York}
      
      # Logging
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      
      # Pi-specific optimizations
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      
    volumes:
      # Persist N8n data
      - n8n_data:/home/node/.n8n
      # Optional: Mount local files for custom nodes
      # - ./custom-nodes:/home/node/.n8n/custom
      # Optional: Mount workflows backup directory
      # - ./workflows-backup:/home/node/.n8n/workflows
      
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
        
    networks:
      - n8n_network
    
    # Resource limits for Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    
    # Health check for N8n
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Watchtower for automatic updates (optional)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: n8n_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400 # Check for updates daily
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: n8n_rpi n8n_postgres_rpi n8n_redis_rpi
    networks:
      - n8n_network

volumes:
  n8n_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  n8n_network:
    driver: bridge